[build.targets.sdist]
include = ["openworld_tshm", "README.md", "LICENSE"]

[envs.default]
dependencies = ["pytest", "ruff"]

[envs.test]
dependencies = ["pytest", "pytest-cov"]

[envs.lint]
dependencies = ["ruff"]


