site_name: OpenWorld TSHM Docs
theme:
  name: mkdocs
nav:
  - Home: index.md
  - User: user.md
  - Operator: ops.md
  - Developer: dev.md
  - Security: security.md
  - Architecture: architecture.md
  - CLI Usage: cli_usage.md
  - Dashboard Guide: dashboard_guide.md
plugins: []
